name: Kubeflow_v1

on:
  workflow_dispatch:
    inputs:
      team_name:
        description: 'Name of your team'
        required: true
      initiative_name:
        description: 'Name of the initiative'
        required: true
      intitiative_id:
        description: 'Initiative Id'
        required: true

jobs:
  kubeflow-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create a branch
        run: | 
          git checkout -b feature-branch
        
      - name: Create config.json
        run: |
          mkdir -p "${{ github.event.inputs.team_name }}/${{ github.event.inputs.initiative_name }}"
          echo '{
            "team_name": "${{ github.event.inputs.team_name }}",
            "initiative_name": "${{ github.event.inputs.initiative_name }}",
            "initiative_id": "${{ github.event.inputs.initiative_id }}"
          }' > "${{ github.event.inputs.team_name }}/${{ github.event.inputs.initiative_name }}/config.json"
        
      - name: Commit and push changes
        run: |
          git add "${{ github.event.inputs.team_name }}/${{ github.event.inputs.initiative_name }}/config.json"
          git commit -m 'Add config.json file'
          git push origin feature-branch
          
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: created config file
          branch: feature-branch
        

    
