name: Kubeflow_v1

on:
  workflow_dispatch:
    inputs:
      team_name:
        description: 'Name of your team'
        required: true
      initiative_name:
        description: 'Name of the initiative'
        required: true
      initiative_id:
        description: 'Initiative Id'
        required: true

jobs:
  kubeflow-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create a branch
        run: | 
          git checkout -b "feature-branch/${{github.event.inputs.team_name}}-${{github.event.inputs.initiative_id}}"
          echo BRANCH_NAME
        
      - name: Create config.json
        run: |
          mkdir -p "${{ github.event.inputs.team_name }}/${{ github.event.inputs.initiative_name }}"
          echo '{
            "team_name": "${{ github.event.inputs.team_name }}",
            "initiative_name": "${{ github.event.inputs.initiative_name }}",
            "initiative_id": "${{ github.event.inputs.initiative_id }}"
          }' > "${{ github.event.inputs.team_name }}/${{ github.event.inputs.initiative_name }}/config.json"

      - name: Check if argoCD appset exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with: 
          files: "cloud_sql/some.py"

      - name: file exists
        if: steps.check_files.outputs.file_exists == 'true'
        run: echo Argo CD file exists
        
      - name: Commit and push changes
        run: |
          git fetch origin
          git add "${{ github.event.inputs.team_name }}/${{ github.event.inputs.initiative_name }}/config.json"
          git commit -m 'Add config.json file'
          
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: created config file
          branch: "feature-branch/${{github.event.inputs.team_name}}-${{github.event.inputs.initiative_id}}"
          base: main
        

    
